# generated by datamodel-codegen:
#   filename:  launch.json
#   timestamp: 2025-02-13T11:51:09+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any, Dict, List

from pydantic import BaseModel, Field, RootModel


class Arg(BaseModel):
    name: str
    value: str | SubstitutionPattern


class Argument(BaseModel):
    name: str
    default: str | float | bool | SubstitutionPattern | None = None
    description: str | None = None
    choices: List[str | float | bool] | None = None


class Condition(BaseModel):
    condition: Condition1 | str | SubstitutionPattern
    actions: (
        List[
            Node | IncludeFile | Argument | Group | SetEnv | SetRemap | Let | Condition
        ]
        | None
    ) = None


class Condition1(Enum):
    unless = "unless"
    if_ = "if"


class Group(BaseModel):
    scoped: bool | None = None
    actions: (
        List[
            Node | IncludeFile | Argument | Group | SetEnv | SetRemap | Let | Condition
        ]
        | None
    ) = None


class IncludeFile(BaseModel):
    file: str | SubstitutionPattern
    pass_all_arguments: bool | None = None
    arg: List[Arg] | None = None


class Launch(BaseModel):
    version: Annotated[str | None, Field(pattern="^[0-9]+\\.[0-9]+\\.[0-9]+$")] = None
    elements: List[
        Node | IncludeFile | Argument | Group | SetEnv | SetRemap | Let | Condition
    ]


class Let(BaseModel):
    name: str
    value: str | SubstitutionPattern


class Node(BaseModel):
    package: str | SubstitutionPattern
    executable: str | SubstitutionPattern
    name: str | SubstitutionPattern | None = None
    namespace: str | SubstitutionPattern | None = None
    exec_name: str | SubstitutionPattern | None = None
    respawn: bool | None = None
    respawn_delay: Annotated[float | None, Field(ge=0.0)] = None
    remappings: List[Remapping] | None = None
    parameters: (
        List[
            Dict[str, str | float | bool | List | Dict[str, Any] | SubstitutionPattern]
            | str
            | SubstitutionPattern
        ]
        | None
    ) = None
    extra_arguments: List[str | SubstitutionPattern] | None = None
    ros_arguments: List[str | SubstitutionPattern] | None = None
    arguments: List[str | SubstitutionPattern] | None = None


class ROS2LaunchFileSchema(BaseModel):
    """
    JSON Schema for ROS2 launch files supporting substitutions and dynamic configurations
    """

    launch: Launch


class Remapping(BaseModel):
    from_: Annotated[str | SubstitutionPattern, Field(alias="from")]
    to: str | SubstitutionPattern


class SetEnv(BaseModel):
    name: str
    value: str | SubstitutionPattern


class SetRemap(BaseModel):
    from_: Annotated[str | SubstitutionPattern, Field(alias="from")]
    to: str | SubstitutionPattern


class SubstitutionPattern(RootModel[str]):
    root: Annotated[
        str,
        Field(
            pattern="^\\$\\((find|exec|env|var|eval|command|find_executable|find_package_share|here|log|var|python|command_line)\\s+[^)]+\\)$"
        ),
    ]


Condition.model_rebuild()
Group.model_rebuild()
Launch.model_rebuild()
