from __future__ import annotations

from Cython.Build.BuildExecutable import (
    DEBUG,
    PythonBuildConfig,
    PYTHON_BUILD_CONFIG,
    INCDIR,
    LIBDIR1,
    LIBDIR2,
    PYLIB,
    PYLIB_DYN,
    CC,
    CFLAGS,
    LINKCC,
    LIBS,
    SYSLIBS,
    LINKFORSHARED,
    EXE_EXT,
    find_python_library,
    resolve_mac_executable_path,
    find_all_libpython_paths,
    runcmd,
    ccompile,
    clink,
    cycompile,
    compile_shared,
    exec_file,
    build,
    build_and_run,
    build_from_argv,
    _build,
    _parse_args,
    safe_print,
    dump_config,
    main,
)

__all__ = [
    "DEBUG",
    "PythonBuildConfig",
    "PYTHON_BUILD_CONFIG",
    "INCDIR",
    "LIBDIR1",
    "LIBDIR2",
    "PYLIB",
    "PYLIB_DYN",
    "CC",
    "CFLAGS",
    "LINKCC",
    "LIBS",
    "SYSLIBS",
    "LINKFORSHARED",
    "EXE_EXT",
    "find_python_library",
    "resolve_mac_executable_path",
    "find_all_libpython_paths",
    "runcmd",
    "ccompile",
    "clink",
    "cycompile",
    "compile_shared",
    "exec_file",
    "build",
    "build_and_run",
    "build_from_argv",
    "_build",
    "_parse_args",
    "safe_print",
    "dump_config",
    "main",
]


if __name__ == "__main__":
    main()
