# generated by datamodel-codegen:
#   filename:  pyproject.json
#   timestamp: 2025-03-10T09:23:23+00:00

# generated by datamodel-codegen:
#   filename:  pyproject.json
#   timestamp: 2024-11-20T02:30:19+00:00

from __future__ import annotations

PYDANTIC = False
try:
    import pydantic

    PYDANTIC = True
except ImportError:
    pass
from array import array
from types import EllipsisType
from typing_extensions import (
    Annotated,
    Any,
    Dict,
    List,
    TYPE_CHECKING,
    dataclass_transform,
    TypeVar,
    Generic,
    Sequence,
    TypedDict,
    Mapping,
    Tuple,
)
from dataclasses import asdict
from functools import lru_cache
import json
from mbcore.collect import namespace
from mbcore.more import first_true

if not TYPE_CHECKING:
    try:
        from pydantic import (
            AnyUrl,
            BaseModel,
            ConfigDict,
            Field,
            RootModel,
            StringConstraints,
            conint,
            constr,
        )

        DataModel = BaseModel
        PYDANTIC = True
    except ImportError:
        from dataclasses import dataclass, field as Field

        PYDANTIC = False
        ConfigDict = dict
        AnyUrl = str
        StringConstraints = Annotated
        coint = int
        constr = str

else:
    pass


@lru_cache(maxsize=128)
def org_and_repo_from_url(url: str) -> Tuple[str, str]:
    parts = url.split("github.com/", 1)[-1].split("/")
    if len(parts) < 2:
        raise ValueError(f"Invalid GitHub URL format: {url}")

    org_ = parts[0]
    repo_ = parts[1]
    if ".git" in repo_:
        repo_ = repo_.split(".git")[0]
    if "#" in repo_:
        repo_ = repo_.split("#")[0]
    return (org_, repo_)


class ConfigDict(TypedDict, total=False):
    """A TypedDict for configuring Pydantic behaviour."""

    title: str | None
    """The title for the generated JSON schema, defaults to the model's name"""

    model_title_generator: Callable[[type], str] | None
    """A callable that takes a model class and returns the title for it. Defaults to `None`."""

    field_title_generator: Callable[[str, FieldInfo | ComputedFieldInfo], str] | None
    """A callable that takes a field's name and info and returns title for it. Defaults to `None`."""

    str_to_lower: bool
    """Whether to convert all characters to lowercase for str types. Defaults to `False`."""

    str_to_upper: bool
    """Whether to convert all characters to uppercase for str types. Defaults to `False`."""

    str_strip_whitespace: bool
    """Whether to strip leading and trailing whitespace for str types."""

    str_min_length: int
    """The minimum length for str types. Defaults to `None`."""

    str_max_length: int | None
    """The maximum length for str types. Defaults to `None`."""

    extra: ExtraValues | None
    """
    Whether to ignore, allow, or forbid extra attributes during model initialization. Defaults to `'ignore'`.

    You can configure how pydantic handles the attributes that are not defined in the model:

    * `allow` - Allow any extra attributes.
    * `forbid` - Forbid any extra attributes.
    * `ignore` - Ignore any extra attributes.
    """


from dataclasses import dataclass, Field as _Field

T = TypeVar("T")


def resolve_origin(tp: Any, dataclass_type: Any = None) -> Any:
    base = dataclass_type
    while hasattr(base, "__origin__"):
        if "Union" in str(base.__origin__) or "Annotated" in str(base.__origin__):
            break
        base = base.__origin__

    while "Optional" in str(base):
        base = base.__args__[0]

    strbase = str(base).split(".")
    strbase = (
        strbase[1]
        if len(strbase) > 2
        else strbase[-1]
        if len(strbase) > 1
        else strbase[0]
    )
    if any(
        str(strbase).split(".")[-1].startswith(c)
        for c in ("List", "Dict", "Tuple", "Sequence", "array")
    ):
        return list

    if any(str(strbase).split(".")[-1].startswith(c) for c in ("Dict", "Mapping")):
        return dict
    return base


def resolve_type(tp: Any, v=None) -> Any:
    if isinstance(tp, str):
        tp = eval(tp)

    while hasattr(tp, "__args__"):
        if isinstance(tp, str):
            tp = eval(tp)
        if any(
            c in str(tp) for c in ("List", "Dict", "Tuple", "Sequence", "array")
        ) or (
            isinstance(tp, type)
            and issubclass(tp, (List, Dict, Tuple, Sequence, array))
        ):
            break
        if isinstance(getattr(tp, "__args__", [None])[0], type) and isinstance(
            v, getattr(tp, "__args__", [None])[0]
        ):
            break
        tp = tp.__args__[0]
    tp = getattr(tp, "__origin__", tp)
    tp = eval(tp) if isinstance(tp, str) else tp
    return tp


class DField(_Field):
    def __init__(
        self, default: EllipsisType | Any = ..., title: str | None = None, **kwargs
    ):
        self.alias = kwargs.pop("alias", None)
        self.title = kwargs.pop("title", title)
        # default_factory', 'init', 'repr', 'hash', 'compare', 'metadata', and 'kw_only'
        default = default if default is not ... else kwargs.pop("default", ...)
        default_factory = kwargs.pop("default_factory", ...)
        init = kwargs.pop("init", True)
        repr = kwargs.pop("repr", True)
        hash = kwargs.pop("hash", None)
        compare = kwargs.pop("compare", True)
        metadata = kwargs.pop("metadata", None)
        kw_only = kwargs.pop("kw_only", False)

        super().__init__(
            default=default,
            default_factory=default_factory,
            init=init,
            repr=repr,
            hash=hash,
            compare=compare,
            metadata=metadata,
            kw_only=kw_only,
        )


def Field(default: Any = ..., title: str | None = None, **kwargs) -> Any:
    return DField(default=default, title=title, **kwargs)


@dataclass_transform(field_specifiers=(Field,))
class DCMeta(type):
    def __new__(cls, name, bases, dct):
        cls = type.__new__(cls, name, bases, dct)

        return dataclass(cls)

        def __init__(self, *args, **kwargs):
            kwds = {}
            for k, v in kwargs.items():
                dataclass_type = cls.__dataclass_fields__[k].type
                dataclass_type = (
                    eval(dataclass_type)
                    if isinstance(dataclass_type, str)
                    else dataclass_type
                )
                if dataclass_type in (str, int, float, bool, bytes, Any) or str(
                    dataclass_type
                ).split(".")[-1] in ("str", "int", "float", "bool", "bytes", "Any"):
                    kwds[k] = v
                    continue
                tp = dataclass_type
                if hasattr(tp, "__dataclass_fields__"):
                    kwds[k] = tp(**v)
                    continue
                if isinstance(tp, str):
                    tp = eval(tp)
                if not isinstance(tp, type) or not isinstance(v, tp):
                    tp = cls.__dataclass_fields__[k].type
                    tp = resolve_type(tp, v)
                    if isinstance(
                        v, list | tuple | Sequence | array
                    ) and not isinstance(v, str | bytes):
                        item_tp = resolve_type(
                            dataclass_type.__args__[0], next(iter(v), None)
                        )
                        if not isinstance(next(iter(v), None), item_tp):
                            kwds[k] = tp(
                                [
                                    item_tp(**i) if isinstance(i, Mapping) else i
                                    for i in v
                                ]
                            )
                        else:
                            kwds[k] = v
                        continue

                    tp = resolve_type(tp, v)
                    if "Union" in str(tp):
                        tp = resolve_type(dataclass_type.__args__[0], v)

                    base = resolve_origin(tp, dataclass_type)
                    tp = resolve_type(dataclass_type, v)

                    kwds[k] = base(**v) if isinstance(v, Mapping) else v

                else:
                    kwds[k] = v

            return init(self, *args, **kwargs)

        cls.__init__ = __init__
        return cls


class BaseModel(namespace[T], Generic[T], metaclass=DCMeta):
    def model_dump(self, **kwargs) -> dict[str, Any]:
        return asdict(self)

    def model_dump_json(self, **kwargs) -> str:
        return json.dumps(asdict(self), **kwargs)


class Author(BaseModel):
    name: str
    email: EmailStr


class BuildSystem(BaseModel):
    requires: Sequence[str]
    build_backend: Annotated[str, Field(alias="build-backend")]


class EntryPoints(BaseModel):
    console_scripts: Sequence[str] | None = None


class License(BaseModel):
    text: str


class Repository(BaseModel):
    org: str
    repo: str
    url: AnyUrl
    branches: Sequence[str] | None = None


class Urls(BaseModel):
    documentation: Annotated[AnyUrl | None, Field(alias="Documentation")] = None
    repository: Annotated[AnyUrl | None, Field(alias="Repository")] = None
    changelog: Annotated[AnyUrl | None, Field(alias="Changelog")] = None
    issues: Annotated[AnyUrl | None, Field(alias="Issues")] = None


class Project(BaseModel):
    name: str
    version: Annotated[str, Field(pattern="^\\d+\\.\\d+\\.\\d+$")]
    description: str | None = None
    readme: str | None = None
    requires_python: Annotated[str, Field(alias="requires-python")] | None = None
    license: License | None = None
    authors: Sequence[Author] | None = None
    classifiers: Sequence[str] | None = None
    dependencies: Sequence[str] | None = None
    optional_dependencies: Annotated[
        Mapping[str, Sequence[str]] | None, Field(alias="optional-dependencies")
    ] = None
    entry_points: Annotated[EntryPoints | None, Field(alias="entry-points")] = None
    urls: Urls | None = None
    scripts: Mapping[str, str] | None = None


@dataclass
class PyProject:
    project: Project = _Field(default_factory=Project)
    build_system: BuildSystem = Field(..., alias="build-system")
    tool: Annotated[dict[str, Any], Field(alias="tool")] = None
    dependency_groups: Annotated[
        dict[str, list[str]], Field(alias="dependency-groups")
    ] = None
    repository: Repository | None = None

    def __post_init__(self, **_kwargs):
        print(type(self).__dataclass_fields__)
        print(type(self.project))
        {
            setattr(
                self,
                k,
                type(self).__dataclass_fields__[k].type(**v)
                if isinstance(v, Mapping)
                else v,
            )
            for k, v in _kwargs.items()
        }
        if self.project.urls is not None:
            github_url = first_true(self.project.urls, lambda x: "github" in x)

            if github_url:
                org, repo = org_and_repo_from_url(github_url)
                self.repository = Repository(org=org, repo=repo, url=github_url)
        return self

    model_post_init = __post_init__

    @classmethod
    def fromtoml(cls, path: Path | str | None = None) -> PyProject:
        if path is None:
            from mbpy.pkg.toml import find_toml

            path = find_toml()
        if path is None:
            raise ValueError("No path provided and no pyproject.toml found.")
        import tomlkit

        path = Path(str(path)).resolve()
        with path.open() as f:
            data = tomlkit.loads(f.read()).unwrap()
        return cls(**data)


if __name__ == "__main__":
    import tomlkit
    from pathlib import Path
    from mbcore.collect import mapkeys

    with Path("pyproject.toml").open() as f:
        data = tomlkit.loads(f.read()).unwrap()

        m = PyProject(**mapkeys(lambda x: x.replace("-", "_"), data))

        print(m.model_dump_json(indent=2))
        print(m.model_dump())

        m = PyProject.fromtoml()
        print(m.model_dump_json(indent=2))
