# generated by datamodel-codegen:
#   filename:  pyproject.json
#   timestamp: 2025-03-10T09:23:23+00:00

# generated by datamodel-codegen:
#   filename:  pyproject.json
#   timestamp: 2024-11-20T02:30:19+00:00

from __future__ import annotations

from functools import lru_cache as _lru_cache
from types import EllipsisType
from typing_extensions import (
    Annotated,
    Any,
    TYPE_CHECKING,
    TypedDict,
    dataclass_transform,
    TypeVar,
    Sequence,
    Mapping,
)
from mbcore.collect import mapkeys
from abc import ABCMeta
from dataclasses import asdict
import json
from mbcore.collect import namespace
from mbcore.more import first_true
from mbcore.types import wraps
from dataclasses import dataclass, Field as _Field, fields, field, InitVar

PYDANTIC = False
try:
    import pydantic

    PYDANTIC = True
except ImportError:
    pass

# if not TYPE_CHECKING:
    # try:
    #     from pydantic import (
    #         AnyUrl,
    #         BaseModel,
    #         ConfigDict,
    #         Field,
    #         RootModel,
    #         StringConstraints,
    #         conint,
    #         constr,
    #         EmailStr,
    #     )

    #     DataModel = BaseModel
    #     PYDANTIC = True
    # except ImportError:
    #     from dataclasses import dataclass, field as Field

    #     PYDANTIC = False
    #     ConfigDict = dict
    #     AnyUrl = str
    #     StringConstraints = Annotated
    #     coint = int
    #     constr = str
    #     EmailStr = str

    # def ParamSpec(*args, **kwargs):
    #     return Any

    # def TypeVar(*args, **kwargs):
    #     return Any

    # def Callable(*args, **kwargs):
    #     return Any

# else:
from typing_extensions import Callable, ParamSpec, TypeVar

FieldInfo = Any
ComputedFieldInfo = Any
ExtraValues = Any


P = ParamSpec("P")
T = TypeVar("T")


def lru_cache(maxsize: int | None = None) -> "Callable[[Callable[P,T]],Callable[P,T]]":
    return _lru_cache(maxsize=maxsize)  # type: ignore # noqa


def org_and_repo_from_url(url: str) -> tuple[str, str]:
    parts = url.split("github.com/", 1)[-1].split("/")
    if len(parts) < 2:
        raise ValueError(f"Invalid GitHub URL format: {url}")

    org_ = parts[0]
    repo_ = parts[1]
    if ".git" in repo_:
        repo_ = repo_.split(".git")[0]
    if "#" in repo_:
        repo_ = repo_.split("#")[0]
    return (org_, repo_)


class ConfigDict(TypedDict, total=False):
    """A TypedDict for configuring Pydantic behaviour."""

    title: str | None
    """The title for the generated JSON schema, defaults to the model's name"""

    model_title_generator: Callable[[type], str] | None
    """A callable that takes a model class and returns the title for it. Defaults to `None`."""

    field_title_generator: Callable[[str, FieldInfo | ComputedFieldInfo], str] | None
    """A callable that takes a field's name and info and returns title for it. Defaults to `None`."""

    str_to_lower: bool
    """Whether to convert all characters to lowercase for str types. Defaults to `False`."""

    str_to_upper: bool
    """Whether to convert all characters to uppercase for str types. Defaults to `False`."""

    str_strip_whitespace: bool
    """Whether to strip leading and trailing whitespace for str types."""

    str_min_length: int
    """The minimum length for str types. Defaults to `None`."""

    str_max_length: int | None
    """The maximum length for str types. Defaults to `None`."""

    extra: ExtraValues | None
    """
    Whether to ignore, allow, or forbid extra attributes during model initialization. Defaults to `'ignore'`.

    You can configure how pydantic handles the attributes that are not defined in the model:

    * `allow` - Allow any extra attributes.
    * `forbid` - Forbid any extra attributes.
    * `ignore` - Ignore any extra attributes.
    """


class DCField(_Field):
    def __init__(
        self, default: EllipsisType | Any = ..., title: str | None = None, **kwargs
    ):
        self.alias = kwargs.pop("alias", None)
        self.title = kwargs.pop("title", title)
        # default_factory', 'init', 'repr', 'hash', 'compare', 'metadata', and 'kw_only'
        default = default if default is not ... else kwargs.pop("default", ...)
        default_factory = kwargs.pop("default_factory", ...)
        init = kwargs.pop("init", True)
        repr = kwargs.pop("repr", True)
        hash = kwargs.pop("hash", None)
        compare = kwargs.pop("compare", True)
        metadata = kwargs.pop("metadata", None)
        kw_only = kwargs.pop("kw_only", False)

        super().__init__(
            default=default,
            default_factory=default_factory,
            init=init,
            repr=repr,
            hash=hash,
            compare=compare,
            metadata=metadata,
            kw_only=kw_only,
        )


T = TypeVar("T")


@wraps(field)
def Field(default: Any = ..., title: str | None = None, **kwargs) -> Any:
    return DCField(default=default, title=title, **kwargs)


def unwrap(tp):
    orig = eval(tp) if isinstance(tp, str) else tp
    if isinstance(tp, str):
        tp = eval(tp)
    if hasattr(tp, "__origin__"):
        tp = tp.__origin__
    if hasattr(tp, "__args__"):
        tp = tp.__args__[0]
    if hasattr(tp, "__metadata__"):
        tp = tp.__metadata__[0]
        return unwrap(tp)
    if any(
        str(tp).startswith(x)
        for x in ["typing.Union", "typing.Optional", "Union", "Optional"]
    ):
        tp = orig.__args__[0]

    return tp if isinstance(tp, type) else tp.__origin__


@dataclass_transform(field_specifiers=(Field, InitVar))
class DCMeta(ABCMeta):
    __dataclass_fields__: dict[str, _Field]
    __pydantic_fields__: dict[str, FieldInfo]

    def __new__(cls, name, bases, dct):
        cls = super(DCMeta, cls).__new__(cls, name, bases, dct)
        cls = dataclass()(cls)
        init = cls.__init__
        post_init = getattr(cls, "__post_init__", lambda self: None)
        setattr(cls, "__post_init__", lambda *args, **kwargs: None)

        def __init__(self, *args, **kwargs):
            kwargs = mapkeys(lambda x: x.replace("-", "_").lower(), kwargs)
            init(self, *args, **kwargs)
            for k, v in kwargs.items():
                if cls.__dataclass_fields__.get(k):
                    tp = cls.__dataclass_fields__[k].type
                    tp = unwrap(tp)
                    if issubclass(tp, BaseModel):
                        v = tp(**v) if isinstance(v, dict) else v
                        setattr(self, k, v)
                    else:
                        setattr(self, k, v)
                elif hasattr(self, k):
                    setattr(self, k, v)
            if post_init is not None:
                post_init(self, **kwargs)

        cls.__init__ = __init__
        return cls


class BaseModel(namespace, metaclass=DCMeta):
    def model_dump(self, **kwargs) -> dict[str, Any]:
        return asdict(self)

    def model_dump_json(self, **kwargs) -> str:
        return json.dumps(asdict(self), **kwargs)


if TYPE_CHECKING:

    def PrivateAttr(default: Any = ...) -> Any:
        return Any

    def computed_field(default: Any = ...) -> Any:
        return Any
else:

    class PrivateAttr(DCField):
        pass

    def computed_field(*args, **kwargs) -> Any:
        try:
            return property(*args, **kwargs)
        except:
            return property(lambda self: getattr(self, args[0]))


@dataclass
class UrlConstraints:
    """Url constraints.

    Attributes:
        max_length: The maximum length of the url. Defaults to `None`.
        allowed_schemes: The allowed schemes. Defaults to `None`.
        host_required: Whether the host is required. Defaults to `None`.
        default_host: The default host. Defaults to `None`.
        default_port: The default port. Defaults to `None`.
        default_path: The default path. Defaults to `None`.
    """

    max_length: int | None = None
    allowed_schemes: list[str] | None = None
    host_required: bool | None = None
    default_host: str | None = None
    default_port: int | None = None
    default_path: str | None = None

    def __hash__(self) -> int:
        return hash(
            (
                self.max_length,
                tuple(self.allowed_schemes)
                if self.allowed_schemes is not None
                else None,
                self.host_required,
                self.default_host,
                self.default_port,
                self.default_path,
            )
        )

    @property
    def defined_constraints(self) -> dict[str, Any]:
        """Fetch a key / value mapping of constraints to values that are not None. Used for core schema updates."""
        return {
            field.name: value
            for field in fields(self)
            if (value := getattr(self, field.name)) is not None
        }


AnyUrl = Annotated[str, UrlConstraints]


class Author(BaseModel):
    name: str
    email: "str"


class BuildSystem(BaseModel):
    requires: Sequence[str]
    build_backend: Annotated[str, Field(alias="build-backend")]


class EntryPoints(BaseModel):
    console_scripts: Sequence[str] | None = None


class License(BaseModel):
    text: str


class Repository(BaseModel):
    org: str
    repo: str
    url: "str"
    branches: Sequence[str] | None = None


class Urls(BaseModel):
    documentation: Annotated[AnyUrl | None, Field(alias="Documentation")] = None
    repository: Annotated[AnyUrl | None, Field(alias="Repository")] = None
    changelog: Annotated[AnyUrl | None, Field(alias="Changelog")] = None
    issues: Annotated[AnyUrl | None, Field(alias="Issues")] = None
    source: Annotated[AnyUrl | None, Field(alias="Source")] = None


@dataclass
class Project(BaseModel):
    name: str
    version: Annotated[str, Field(pattern="^\\d+\\.\\d+\\.\\d+$")] | None = None
    description: str | None = None
    readme: str | None = None
    requires_python: Annotated[str, Field(alias="requires-python")] | None = None
    license: License | None = None
    authors: Sequence[Author] | None = None
    classifiers: Sequence[str] | None = None
    dependencies: Sequence[str] | None = None
    optional_dependencies: Annotated[
        Mapping[str, Sequence[str]] | None, Field(alias="optional-dependencies")
    ] = None
    entry_points: Annotated[EntryPoints | None, Field(alias="entry-points")] = None
    urls: Urls | None = None
    scripts: Mapping[str, str] | None = None
    dynamic: Mapping[str, Any] | None = None
    keywords: Sequence[str] | None = None


@dataclass
class PyProject(BaseModel):
    project: Project
    build_system: Annotated[BuildSystem, Field(alias="build-system")]
    tool: Mapping[str, Any] | None = None
    dependency_groups: Annotated[
        Mapping[str, Sequence[str]], Field(alias="dependency-groups")
    ] = None
    repository: Repository | None = None

    def __post_init__(self, **_kwargs):
        if self.project.urls is not None:
            github_url = first_true(self.project.urls, lambda x: "github" in x)

            if github_url:
                org, repo = org_and_repo_from_url(github_url)
                self.repository = Repository(org=org, repo=repo, url=github_url)
        return self

    @classmethod
    def fromtoml(cls, path: Path | str | None = None) -> PyProject:
        from pathlib import Path

        if path is None or Path(str(path)).is_dir():
            from mbpy.pkg.toml import find_toml

            path = find_toml()
        if path is None:
            raise ValueError("No path provided and no pyproject.toml found.")
        import tomlkit

        path = Path(str(path)).resolve()
        data = tomlkit.loads(path.read_text()).unwrap()
        return cls(**data)


if __name__ == "__main__":
    import tomlkit
    from pathlib import Path

    with Path("pyproject.toml").open() as f:
        data = tomlkit.loads(f.read()).unwrap()

        m = PyProject(**data)

        print(type(Project(**m.project)))
        print(m.project)
        print(m.model_dump_json(indent=2))
        print(PyProject.fromtoml())

    data = PyProject.fromtoml(
        "/Users/sebastianperalta/simply/corp/projects/mbnew/pyproject.toml"
    )
    print(data)
