# generated by datamodel-codegen:
#   filename:  mb.json
#   timestamp: 2025-02-13T11:55:44+00:00

from __future__ import annotations

from enum import Enum, StrEnum
from pathlib import Path
from typing import Annotated, Any

from pydantic import AnyUrl, BaseModel, ConfigDict, Field, RootModel


def compose(func, *funcs):
    return lambda x: func(compose(*funcs)(x)) if funcs else func(x)


def attrgetter(attr):
    return lambda x: getattr(x, attr)


class Build(BaseModel):
    """Build configurations."""

    model_config = ConfigDict(
        extra="forbid",
    )
    build_directory: Annotated[
        str | None, Field(alias="buildDirectory", pattern="^\\/[^\\s]*$")
    ] = "${HOME}/mb_build"
    """
    Directory where build artifacts are stored.
    """
    install_directory: Annotated[
        str | None, Field(alias="installDirectory", pattern="^\\/[^\\s]*$")
    ] = "${HOME}/mb_output"
    """
    Directory where output binaries are placed.
    """


class CCConfigurationSchema(BaseModel):
    compiler: Compiler | None = None
    field_defs: Annotated[Any | None, Field(alias="$defs")] = None
    additional_properties: Annotated[
        Any | None, Field(alias="additionalProperties")
    ] = None


class Compiler(BaseModel):
    name: str | None = {"$dynamicRef": "#/$defs/cppCompiler/name"}
    """
    Name of the C/C++ compiler.
    """
    version: str | None = {"$dynamicRef": "#/$defs/cppStandard/version"}
    """
    Version of the C/C++ compiler.
    """
    additional_properties: Annotated[
        Any | None, Field(alias="additionalProperties")
    ] = None


class Cpp(RootModel[CCConfigurationSchema]):
    root: CCConfigurationSchema


class License(Enum):
    """License of the project."""

    mit = "MIT"
    apache_2_0 = "Apache-2.0"
    gpl_3_0 = "GPL-3.0"
    bsd_3_clause = "BSD-3-Clause"
    proprietary = "Proprietary"


class MBConfigurationSchema(BaseModel):
    """Schema for managing the main MB project configurations."""

    model_config = ConfigDict(
        extra="forbid",
    )
    cpp: Any
    python: Any

    project: Project
    """Project-specific configurations."""

    environment: Any | None = None

    build: Build
    """Build configurations."""


class PackageManager(StrEnum):
    pip = "pip"
    conda = "conda"
    uv = "uv"
    hatch = "hatch"


class Project(BaseModel):
    """Project-specific configurations."""

    name: Annotated[
        str | None,
        Field(
            pattern="^[a-zA-Z0-9-_]+$",
            default_factory=compose(Path.cwd, attrgetter("stem")),
        ),
    ]
    """Name of the project."""

    version: str | None = "1.0.0"
    """Version of the project."""

    repository: AnyUrl | None = None
    """URL of the project's repository."""

    license: License | None = License.mit
    """License of the project."""


class Python(BaseModel):
    version: Annotated[str | None, Field(pattern="^\\d+\\.\\d+(\\.\\d+)*$")] = "3.11"
    package_manager: Annotated[PackageManager | None, Field(alias="packageManager")] = (
        PackageManager.pip
    )
    virtual_env: Annotated[bool | None, Field(alias="virtualEnv")] = True
    """Use virtual environments."""


class Environment(BaseModel):
    """Environment configurations."""

    model_config = {"extra": "allow"}

    path: Annotated[str | None, Field(alias="PATH")] = "/usr/local/bin:/usr/bin:/bin"
    """Path environment variable."""

    home: Annotated[str | None, Field(alias="HOME")] = "/home/user"
    """Home directory."""

    lang: Annotated[str | None, Field(alias="LANG")] = "en_US.UTF-8"
    """Locale settings."""
