
from mbpy.pkg.graph import RootNode, TreeNode, topo_sort, Graph

# Define a simple type for the content for testing purposes
class DummyContent(dict):
    pass

def test_topo_sort_simple_dag():
    """Tests topological sort on a simple Directed Acyclic Graph (DAG)."""
    # Create a graph: Root -> A -> C, Root -> B -> C
    root = RootNode[DummyContent](name="root", content=DummyContent(path="root_path"))
    node_a = TreeNode[DummyContent](name="A", content=DummyContent(path="a_path"), parent=root)
    node_b = TreeNode[DummyContent](name="B", content=DummyContent(path="b_path"), parent=root)
    # Node C depends on A and B. We model this by adding C as a child of both.
    # This isn't the primary way dependencies are represented (imports are),
    # but topo_sort works on the graph structure. Let's adjust how topo_sort is called.
    # The current graph structure has A and B as children of Root. Let's make C depend on A and B
    # by adding edges in the graph representation used by topo_sort.

    # Let's redefine: Root -> A, Root -> B, A -> C, B -> C
    root_node = RootNode[DummyContent](name="root", content=DummyContent(path="root"))
    node_a = TreeNode[DummyContent](name="A", content=DummyContent(path="A"), parent=root_node)
    node_b = TreeNode[DummyContent](name="B", content=DummyContent(path="B"), parent=root_node)
    node_c = TreeNode[DummyContent](name="C", content=DummyContent(path="C"), parent=node_a) # C child of A initially

    # Manually add the dependency edge B -> C in the adjacency matrix
    # Note: topo_sort relies on the graph structure generated by tograph(),
    # which primarily uses the parent-child relationship and 'imports'.
    # For testing topo_sort directly, we might need a graph representation.
    # Let's simulate the graph that tograph() would produce.

    # Rebuild structure for clarity: Root -> A, Root -> B. Then add C which depends on A, B.
    # topo_sort internally calls tograph(). We need to ensure the graph structure reflects dependencies.
    # Let's create a graph where C 'imports' A and B.
    root_g = RootNode[dict](name="root", content={"path": "root"})
    nodeA = TreeNode[dict](name="A", content={"path": "A", "imports": {}}, parent=root_g)
    nodeB = TreeNode[dict](name="B", content={"path": "B", "imports": {}}, parent=root_g)
    nodeC = TreeNode[dict](name="C", content={"path": "C", "imports": {"A": {}, "B": {}}}, parent=root_g) # C 'imports' A and B

    # Manually add A and B to the root's node map so C's imports can be resolved by tograph
    root_g.nodes["A"] = nodeA
    root_g.nodes["B"] = nodeB
    root_g.nodes["C"] = nodeC


    # Expected order: root, A, B, C (A and B can be swapped)
    sorted_result_lists = topo_sort(root_g) # This returns list of lists (components)
    
    # Flatten the list of lists and get node names
    sorted_nodes = [node.name for sublist in sorted_result_lists for node in sublist]

    # Possible valid orders:
    expected_order1 = ["root", "A", "B", "C"]
    expected_order2 = ["root", "B", "A", "C"]

    print(f"Sorted Nodes: {sorted_nodes}") # Debug print

    assert sorted_nodes == expected_order1 or sorted_nodes == expected_order2, \
        f"Topological sort order {sorted_nodes} is incorrect. Expected {expected_order1} or {expected_order2}"

def test_topo_sort_cycle():
    """Tests topological sort on a graph with a cycle that needs breaking."""
    # Create a cycle: Root -> A -> B -> A
    root = RootNode[dict](name="root", content={"path": "root"})
    node_a = TreeNode[dict](name="A", content={"path": "A", "imports": {"B": {}}}, parent=root) # A imports B
    node_b = TreeNode[dict](name="B", content={"path": "B", "imports": {"A": {}}}, parent=root) # B imports A

    root.nodes["A"] = node_a
    root.nodes["B"] = node_b

    # break_cycles should remove one edge (e.g., B->A or A->B)
    sorted_result_lists = topo_sort(root)
    sorted_nodes = [node.name for sublist in sorted_result_lists for node in sublist]

    print(f"Sorted Nodes (Cycle): {sorted_nodes}") # Debug print

    # Depending on which edge is broken, the order will vary.
    # If B->A is broken: root, A, B
    # If A->B is broken: root, B, A
    expected_cycle_broken1 = ["root", "A", "B"]
    expected_cycle_broken2 = ["root", "B", "A"]

    assert sorted_nodes == expected_cycle_broken1 or sorted_nodes == expected_cycle_broken2, \
        f"Topological sort order {sorted_nodes} after cycle breaking is incorrect. Expected {expected_cycle_broken1} or {expected_cycle_broken2}"

def test_topo_sort_complex_graph():
    """Tests topological sort on a more complex graph structure."""
    # Graph structure:
    # Root -> A, Root -> B
    # A -> C, A -> D
    # B -> D, B -> E
    # C -> F
    # D -> F
    # E -> F
    # Add a cycle: F -> B to test cycle breaking in a complex graph

    root = RootNode[dict](name="root", content={"path": "root"})
    node_a = TreeNode[dict](name="A", content={"path": "A", "imports": {}}, parent=root)
    node_b = TreeNode[dict](name="B", content={"path": "B", "imports": {}}, parent=root)
    node_c = TreeNode[dict](name="C", content={"path": "C", "imports": {"A": {}}}, parent=root) # Depends on A
    node_d = TreeNode[dict](name="D", content={"path": "D", "imports": {"A": {}, "B": {}}}, parent=root) # Depends on A, B
    node_e = TreeNode[dict](name="E", content={"path": "E", "imports": {"B": {}}}, parent=root) # Depends on B
    # F depends on C, D, E, and introduces a cycle by depending on B (which F influences via E)
    node_f = TreeNode[dict](name="F", content={"path": "F", "imports": {"C": {}, "D": {}, "E": {}, "B": {}}}, parent=root) # Depends on C, D, E, B (cycle F->B)

    # Add nodes to root's map for resolution
    root.nodes["A"] = node_a
    root.nodes["B"] = node_b
    root.nodes["C"] = node_c
    root.nodes["D"] = node_d
    root.nodes["E"] = node_e
    root.nodes["F"] = node_f

    sorted_result_lists = topo_sort(root)
    sorted_nodes = [node.name for sublist in sorted_result_lists for node in sublist]

    print(f"Sorted Nodes (Complex): {sorted_nodes}") # Debug print

    # Expected order analysis:
    # - root must be first.
    # - A and B must come after root.
    # - C must come after A.
    # - D must come after A and B.
    # - E must come after B.
    # - F must come after C, D, E.
    # - The cycle F -> B needs to be broken. 
    #   - If F->B edge is broken: A, B dependencies met first, then C, D, E, then F.
    #   - Possible valid orders depend on the relative order of A/B, C/D/E after their dependencies are met.

    # Check basic dependencies:
    assert sorted_nodes[0] == "root", "Root should be the first node"
    
    # Verify dependencies are respected (simple index checks might be fragile, but give basic idea)
    # More robust checks would involve verifying for every node, its dependencies appear before it.
    def check_deps(sorted_list):
        pos = {name: i for i, name in enumerate(sorted_list)}
        assert pos["A"] > pos["root"]
        assert pos["B"] > pos["root"]
        assert pos["C"] > pos["A"]
        assert pos["D"] > pos["A"] and pos["D"] > pos["B"]
        assert pos["E"] > pos["B"]
        # Check F's dependencies *assuming F->B cycle was broken*
        assert pos["F"] > pos["C"]
        assert pos["F"] > pos["D"]
        assert pos["F"] > pos["E"]
        # We don't assert pos["F"] > pos["B"] because the edge might be broken.
        # If the cycle A->D<-B or B->E->F path is involved in cycle breaking, logic gets complex.
        # topo_sort guarantees *a* valid topological order if one exists after cycle breaking.
        return True

    assert check_deps(sorted_nodes), "Dependency order violated in the complex graph sort."
    
    # Check length
    assert len(sorted_nodes) == 7, "Incorrect number of nodes in the sorted list." 